// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814120917_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Planning", b =>
                {
                    b.Property<int>("PlanningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanningId"));

                    b.Property<string>("CandidateToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlanningId");

                    b.ToTable("Planning", (string)null);
                });

            modelBuilder.Entity("Backend.Models.PlanningSlot", b =>
                {
                    b.Property<int>("PlanningSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanningSlotId"));

                    b.Property<int>("BalancedQuantity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("OriginalQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("PlanningId")
                        .HasColumnType("integer");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SlotOrder")
                        .HasColumnType("integer");

                    b.HasKey("PlanningSlotId");

                    b.HasIndex("PlanningId");

                    b.ToTable("PlanningSlot", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlanningSlot_BalancedQuantity_NonNegative", "\"BalancedQuantity\" >= 0");

                            t.HasCheckConstraint("CK_PlanningSlot_OriginalQuantity_NonNegative", "\"OriginalQuantity\" >= 0");
                        });
                });

            modelBuilder.Entity("Backend.Models.PlanningSlot", b =>
                {
                    b.HasOne("Backend.Models.Planning", "Planning")
                        .WithMany("Slots")
                        .HasForeignKey("PlanningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planning");
                });

            modelBuilder.Entity("Backend.Models.Planning", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
